"use client";
import { QueryClient, QueryClientProvider } from "react-query";
import { Inter } from "next/font/google";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

import Button from "@/components/Button/Button";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });
const queryClient = new QueryClient();

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();

  useEffect(() => {
    const bearerToken = localStorage.getItem("token");

    if (!bearerToken) {
      router.push("/login");
    }
  }, [router]);

  return <>{children}</>;
}
